### PR TITLE
Migration of trusted artifacts to entitlements-api-go pipeline

### PR DESCRIPTION
**Pull request by Ellen-Yi-Dong**
# Platform Security
Use trusted artifacts within the tekton pipeline in order to try to run the unit tests 
- in future usage, will eventually just use the trusted artifacts instead of using workspaces

### CODE REVIEW

**Comment by Ellen-Yi-Dong** [comment]
Note for me: https://github.com/RedHatInsights/entitlements-api-go/pull/220 merge this PR first 
(this will solve the bonfire-tekton integration test failure)

**Review by astrozzc — APPROVED** [review]

**Pull request merged**
