### PR TITLE
Adding new ansible SKUs

### PR DESCRIPTION
**Pull request by abenokraitis**
Adding two new Ansible SKUs (Red Hat Ansible Automation Self Support and Standard NFR for partners only)

### CODE REVIEW

**Comment by abenokraitis** [comment]
Thanks very much for the review - I'm not in the know on merge schedules, does this need to be assigned to a sprint or similar? Thanks! (@catastrophe-brandon )

**Comment by tahmidefaz** [comment]
Hi, @abenokraitis is this good for merge? Adding @coderbydesign for review, as he is maintaining this project now

**Comment by abenokraitis** [comment]
I believe this should be good to merge from an Ansible standpoint! :-) Thanks @tahmidefaz and @coderbydesign !

**Comment by tahmidefaz** [comment]
@abenokraitis Cool! Thanks for the update! If everything looks good, I think @coderbydesign can merge it in and deploy it for you :slightly_smiling_face:

**Comment by coderbydesign** [comment]
@lphiri - This is the PR from standup. Assuming there's no other validation required, we can get this in and deploy it.

**Pull request merged**
